name: Validate

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  hassfest:
    name: Hassfest
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v7

      - name: Run Hassfest
        uses: home-assistant/actions/hassfest@master

  hacs:
    name: HACS Validation
    runs-on: ubuntu-latest

    steps:
      - name: HACS validation
        uses: hacs/action@main
        with:
          category: integration

  prek:
    name: Prek
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Check out repository
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Run prek
        uses: j178/prek-action@v3.0.0

  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"

      - name: Install pytest
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_test.txt

      - name: Run tests
        run: pytest
